# Generated by Django 5.2.3 on 2025-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
