services:
  db_todoapp:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    restart: always

  web_todoapp:
    build:
      context: ..
      dockerfile: Docker/backend/Dockerfile
    command: >
      sh -c "cd todo &&
             python manage.py migrate &&
             gunicorn todo.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_todoapp
    env_file:
      - ./.env

  frontend_todoapp:
    build:
      context: ..
      dockerfile: Docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web_todoapp
    restart: always

volumes:
  postgres_data:
