
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: ..
      dockerfile: Docker/backend/Dockerfile
    command: >
      sh -c "cd todo &&
             python manage.py migrate &&
             gunicorn todo.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - DATABASE_HOST=db
      - DATABASE_NAME=todo_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password

volumes:
  postgres_data:
